### PR TITLE
Feature/syntax highlight

### PR DESCRIPTION
**Pull request by Intelligent2013**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
@Intelligent2013 can we dynamically fetch highlightjs on build, without copying in the code in the repository? Thanks

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can we dynamically fetch highlightjs on build, without copying in the code in the repository? Thanks

@ronaldtse yes, sure.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can we dynamically fetch highlightjs on build, without copying in the code in the repository? Thanks

@ronaldtse done.

**Comment by Intelligent2013** [comment]
> Thanks @Intelligent2013 ! Seems that Windows builds are currently failing.

The error occurs on the fontist installation stage:
```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.1-x64-unknown.gemspec.rz)
```

but the correct link is https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.1-x64-mingw32.gemspec.rz
It seems 'gem install' can't determine platform properties. I've create the issue: https://github.com/fontist/fontist/issues/278
This issue doesn't relate directly to this PR, so I'll merge it.

**Pull request merged**
