### PR TITLE
Incorporate Source Han Sans in package

### PR DESCRIPTION
**Pull request by ronaldtse**
Font is now downloaded on package build, but needs to replace:
* NanumGothic
* DroidSans

Inside the source code and PDF config XML.

@Intelligent2013 could you help with this? Thanks!

### CODE REVIEW

**Comment by ronaldtse** [comment]
In particular, need to also include the `SourceHanSans-*.ttc` files here:

```java
    private final ArrayList<String> fontList = new ArrayList<String>() {
        {
            // Example
            // add("SourceSansPro-Regular.ttf");
            Stream.of("Sans", "Serif", "Code").forEach(
                    prefix -> Stream.of("Regular", "Bold", "Italic", "BoldItalic").forEach(
                            suffix -> add(FONT_PREFIX + prefix + FONT_SUFFIX + "-" + suffix + ".ttf"))
            );
        }
    };
```

**Comment by Intelligent2013** [comment]
@ronaldtse Why did you use https://github.com/google/fonts/tree/master/ofl/ instead of https://github.com/adobe-fonts/source-serif-pro? Is this important? In https://github.com/adobe-fonts more latest versions.

**Comment by Intelligent2013** [comment]
In https://github.com/google/fonts/tree/master/ofl/sourceserifpro there isn't a font SourceSerifPro-Italic.ttf, so I propose to use https://github.com/adobe-fonts/ repository. I'll modify makefile.

**Comment by ronaldtse** [comment]
I see, I can fix it later tonight. The adobe-fonts repo didn’t seem to have the TTF files?

**Pull request merged**
