### PR TITLE
Barcode and QRcode processing added

### PR DESCRIPTION
**Pull request by Intelligent2013**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

**Comment by ronaldtse** [comment]
@Intelligent2013 I think we don't need PAT_TOKEN and PAT_USERNAME here.

According to this:
https://github.com/TobseF/HelloMaven/blob/master/settings.xml

As long as the user and token have read access to the package (which is everyone), the package can be fetched.

Is it possible that the barcode4j package isn't being published properly?

**Comment by Intelligent2013** [comment]
> Is it possible that the barcode4j package isn't being published properly?
Hmm... I don't sure that the reason in publishing. I see in log that there is ' Authentication failed' error:
` Authentication failed for https://maven.pkg.github.com/metanorma/barcode4j/net/sf/barcode4j/barcode4j/2.2-SNAPSHOT/barcode4j-2.2-SNAPSHOT.pom 401 Unauthorized
`

I've created two repositories at my account and trying to deep into this problem.

**Comment by ronaldtse** [comment]
There seems to be an issue right now:

```
Downloading from metanorma: https://maven.pkg.github.com/metanorma/barcode4j/junit/junit-dep/maven-metadata.xml
Downloading from central: https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
Downloading from central: https://repo1.maven.org/maven2/net/sf/barcode4j/barcode4j-fop-ext/2.1/barcode4j-fop-ext-2.1.jar
Downloading from central: https://repo1.maven.org/maven2/net/sf/barcode4j/barcode4j/2.3/barcode4j-2.3.jar
Downloading from central: https://repo1.maven.org/maven2/org/apache/avalon/framework/avalon-framework-api/4.3.1/avalon-framework-api-4.3.1.jar
Downloaded from central: https://repo1.maven.org/maven2/org/apache/avalon/framework/avalon-framework-api/4.3.1/avalon-framework-api-4.3.1.jar (33 kB at 32 kB/s)
Downloaded from central: https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar (54 kB at 45 kB/s)
Downloaded from central: https://repo1.maven.org/maven2/net/sf/barcode4j/barcode4j-fop-ext/2.1/barcode4j-fop-ext-2.1.jar (32 kB at 21 kB/s)
Downloading from metanorma: https://maven.pkg.github.com/metanorma/barcode4j/net/sf/barcode4j/barcode4j/2.3/barcode4j-2.3.jar
```

It seems that the `barcode4j-fop-ext` package also needs to be published in our barcode4j?

**Comment by Intelligent2013** [comment]
> There seems to be an issue right now:
> 
> ```
> Downloading from metanorma: https://maven.pkg.github.com/metanorma/barcode4j/junit/junit-dep/maven-metadata.xml
> Downloading from central: https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
> Downloading from central: https://repo1.maven.org/maven2/net/sf/barcode4j/barcode4j-fop-ext/2.1/barcode4j-fop-ext-2.1.jar
> Downloading from central: https://repo1.maven.org/maven2/net/sf/barcode4j/barcode4j/2.3/barcode4j-2.3.jar
> Downloading from central: https://repo1.maven.org/maven2/org/apache/avalon/framework/avalon-framework-api/4.3.1/avalon-framework-api-4.3.1.jar
> Downloaded from central: https://repo1.maven.org/maven2/org/apache/avalon/framework/avalon-framework-api/4.3.1/avalon-framework-api-4.3.1.jar (33 kB at 32 kB/s)
> Downloaded from central: https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar (54 kB at 45 kB/s)
> Downloaded from central: https://repo1.maven.org/maven2/net/sf/barcode4j/barcode4j-fop-ext/2.1/barcode4j-fop-ext-2.1.jar (32 kB at 21 kB/s)
> Downloading from metanorma: https://maven.pkg.github.com/metanorma/barcode4j/net/sf/barcode4j/barcode4j/2.3/barcode4j-2.3.jar
> ```
> 
> It seems that the `barcode4j-fop-ext` package also needs to be published in our barcode4j?

barcode4j-2.3.jar works well with barcode4j-fop-ext-2.1.jar. We don't need to change barcode4j-fop-ext. And then why we need to duplicate jar from maven repo?

**Comment by Intelligent2013** [comment]
> Let’s change the PAT_TOKEN and PAT_USER to GITHUB_TOKEN and GITHUB_USERNAME. This way we won’t depend on PAT_TOKEN anymore.

Regarding GITHUB_TOKEN ( https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret ):

`The token's permissions are limited to the repository that contains your workflow.`

barcode4j is a separate repository from mn2pdf. If we need to use GITHUB_TOKEN, then we need to move barcode4j inside mn2pdf again. As I understood.

**Comment by Intelligent2013** [comment]
@ronaldtse yesterday you wrote that 'in Pull Requests, secrets are not provided'. I propose to merge this PR and continue commit in master.

**Comment by ronaldtse** [comment]
I found out we can use “github.token” instead of GITHUB_TOKEN in a PR, so tests will pass.

**Pull request merged**
