### PR TITLE
Simplify workflow

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #94

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse @Intelligent2013 could you please review my changes:
 - [x] workflow simplified
 - [x] fontist instead platform dependent packages

Open question is that ok that our java on GitHub Packages has 0 downloads? https://github.com/metanorma/mn2pdf/packages/898794 

P.S. add votes for https://github.com/badges/shields/issues/4183

**Comment by ronaldtse** [comment]
> Open question is that ok that our java on GitHub Packages has 0 downloads? 

Because we don't use mn2pdf outside the mn2pdf-ruby gem...

**Comment by CAMOBAP** [comment]
@ronaldtse right! thanks for explanation

**Comment by ronaldtse** [comment]
Awesome work here, thanks @CAMOBAP !

**Pull request merged**
