### PR TITLE
#3 move tests to junit

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #3

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 LGTM. Ping @Intelligent2013 for a review.

**Comment by CAMOBAP795** [comment]
@Intelligent2013 it looks like `pdf_fonts_config.xml` wasn't generated

To be on the same page I didn't remove `test` target from `Makefile`, you still have to call `make test` to run tests

If you have some suggestion to move `envsubst < src/test/resources/pdf_fonts_config.xml.in > src/test/resources/pdf_fonts_config.xml` please let me know

**Comment by Intelligent2013** [comment]
@CAMOBAP795 thank you for the comment.  I'm working on Windows platform and a bit confused how to execute makefile on windows. On Windows there aren't 'make' and 'envsubst' commands. So I've just copied the commands from makefile and run it in cmd. I'm novice in GitHub Actions, so I don't know how to debug and execute it on local Win-platform.

> If you have some suggestion to move `envsubst < src/test/resources/pdf_fonts_config.xml.in > src/test/resources/pdf_fonts_config.xml` please let me know

I've moved environment substitution into pom.xml

**Comment by ronaldtse** [comment]
@intelligent2013 in order to replace envsubst, perhaps we can move the font directory argument (and the functionality of “pdf_font_config.xml”) into within mn2pdf command? Then we don’t need envsubst anymore.

**Comment by CAMOBAP795** [comment]
> On Windows there aren't 'make' and 'envsubst' commands.

@Intelligent2013  Actually you can install them on windows, with https://chocolatey.org/ like `choco install --no-progress make gnuwin32-coreutils.install`, this exactly what was implemented in windows workflow file https://github.com/metanorma/mn2pdf/pull/5/files#diff-222da3d5159ccbea64c56d21b445f986

So, to be on the same page, it worked for windows also, before you did your commits

> I've moved environment substitution into pom.xml

Really good idea

> in order to replace envsubst, perhaps we can move the font directory argument (and the functionality of “pdf_font_config.xml”) into within mn2pdf command?

I think we can put it in jar, one questions is when `MN_PDF_FONT_PATH` substitution should happen? As far as I understood it should happen on runtime, can someone confirm this?

**Comment by ronaldtse** [comment]
@Intelligent2013 @CAMOBAP795 since it's already working let's first merge this and move the remaining task a new one?

**Comment by CAMOBAP795** [comment]
@ronaldtse 100% agree

**Comment by CAMOBAP795** [comment]
Oh it's already done

**Comment by Intelligent2013** [comment]
@ronaldtse 
> in order to replace envsubst, perhaps we can move the font directory argument (and the functionality of “pdf_font_config.xml”) into within mn2pdf command? Then we don’t need envsubst anymore.

We can pass font directory via argument or via MN_PDF_FONT_PATH environment variable. I prefer via environment variable, because we use it also in other scripts for font installation process.

> I think we can put it in jar, one questions is when MN_PDF_FONT_PATH substitution should happen? As far as I understood it should happen on runtime, can someone confirm this?

Yes, font substitution should happen on runtime.

**Comment by CAMOBAP795** [comment]
> Yes, font substitution should happen on runtime.

@Intelligent2013 as far as I understood `pdf_fonts_config.xml` will comes from `metanorma-*` processors (i.e. `metanorma-iso`, `metanorma-ogc` and so on), is that true?

**Comment by ronaldtse** [comment]
> We can pass font directory via argument or via MN_PDF_FONT_PATH environment variable. I prefer via environment variable, because we use it also in other scripts for font installation process.

@Intelligent2013 we are going to move the font installation process into Metanorma proper, so it the usage of this environment variable `MN_PDF_FONT_PATH ` will be de-coupled. We don't need to keep it.

> @Intelligent2013 as far as I understood pdf_fonts_config.xml will comes from metanorma-* processors (i.e. metanorma-iso, metanorma-ogc and so on), is that true?

I'd rather we internalize pdf_fonts_config.xml inside `mn2pdf`? metanorma-* can provide the font path to mn2pdf?

**Comment by ronaldtse** [comment]
Since this issue is already closed, let's move the discussion to #8. Thanks!

**Comment by Intelligent2013** [comment]
> @Intelligent2013 as far as I understood `pdf_fonts_config.xml` will comes from `metanorma-*` processors (i.e. `metanorma-iso`, `metanorma-ogc` and so on), is that true?

@CAMOBAP795 Hmm... I don't sure. I know only that it uses in 'mn-native-pdf'.

**Pull request merged**
